---
title: "LAX Corpus Statistics, CogSci 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(lme4)
# library(arm)
# library(xtable)
library(lmerTest)
library(tidyboot)
```

## People use more words for complex objects

```{r }
df_trial = read.csv('../../results/csv/lax_corpus_1k_trials_cogsci22.csv')
```

```{r}
m1 = lmer(data = df_trial, n_steps ~ domain + (1 | subdomain) + (1 | gameID) )
m2 = lmer(data = df_trial, n_steps ~ domain + trial_num + (1 | subdomain) + (1 | gameID) )
m3 = lmer(data = df_trial, n_steps ~ domain*trial_num + (1 | subdomain) + (1 | gameID) )
anova(m1,m2,m3)
summary(m3)
```

```{r}
m1 = lmer(data = df_trial, char_sum ~ domain + (1 | subdomain) + (1 | gameID) )
m2 = lmer(data = df_trial, char_sum ~ domain + trial_num + (1 | subdomain) + (1 | gameID) )
m3 = lmer(data = df_trial, char_sum ~ domain*trial_num + (1 | subdomain) + (1 | gameID) )
anova(m1,m2,m3)
summary(m3)
```

```{r}
m1 = lmer(data = df_trial, n_whats_filtered ~ domain + (1 | subdomain) + (1 | gameID) )
m2 = lmer(data = df_trial, n_whats_filtered ~ domain + trial_num + (1 | subdomain) + (1 | gameID) )
m3 = lmer(data = df_trial, n_whats_filtered ~ domain*trial_num + (1 | subdomain) + (1 | gameID) )
anova(m1,m2,m3)
summary(m3)
```


```{r}
m1 = lmer(data = df_trial, what_word_sum ~ domain + (1 | subdomain) + (1 | gameID) )
m2 = lmer(data = df_trial, what_word_sum ~ domain + trial_num + (1 | subdomain) + (1 | gameID) )
m3 = lmer(data = df_trial, what_word_sum ~ domain*trial_num + (1 | subdomain) + (1 | gameID) )
anova(m1,m2,m3)
summary(m3)
```

# Comparing program length with description length

```{r}
d.raw <- read_csv('../../results/csv/lax_corpus_1k_trials_program_length.csv') %>%
  select(gameID, stimId, domain, subdomain, what_word_sum, where_word_sum, program_length, dsl) %>%
  mutate(combined_word_sum = what_word_sum + where_word_sum) %>%
  mutate(dsl_numeric = case_when(dsl == 'dsl_0_base' ~ -1.5, 
                                 dsl == 'dsl_1_low'  ~ -0.5, 
                                 dsl == 'dsl_2_mid'  ~  0.5, 
                                 dsl == 'dsl_3_high' ~  1.5))

d <- d.raw %>%
  group_by(gameID) %>%
  mutate(combined_word_sum = scale(combined_word_sum),
         what_word_sum = scale(what_word_sum),
         combined_word_sum = ifelse(is.na(combined_word_sum), 0, combined_word_sum),
         what_word_sum = ifelse(is.na(what_word_sum), 0, what_word_sum)) %>%
  group_by(subdomain, dsl) %>%
  mutate(program_length = scale(program_length)) %>%
  ungroup() %>%
  mutate(subdomain = fct_relevel(subdomain, 'nuts-bolts', 'furniture', 'wheels', 'dials',
                                 'bridge', 'castle', 'city', 'house'))
```
